version: '2'

services:
  server:
    image: registry.gitlab.com/commento/commento:latest
    ports:
      - 443:8443
    environment:
      COMMENTO_ORIGIN: https://commento.room29.art
      COMMENTO_PORT: 443
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
#      COMMENTO_FORBID_NEW_OWNERS: "true"
      VIRTUAL_HOST: commento.room29.art
      LETSENCRYPT_HOST: commento.room29.art
      LETSENCRYPT_EMAIL: admin@sullo.co
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_volume:/vol/data/postgresql/data

volumes:
  postgres_data_volume:
